import { createContext, useContext, useEffect, useMemo, useState } from 'react'
import { mockUsers, mockCourses, mockTeams, mockAssignments, mockCertificates, mockAuditLog, mockLearningPaths } from '../data/index.js'

export const NAV_CONFIG = {
  admin: [
    { id:'dashboard',     en:'Dashboard',          ar:'لوحة التحكم',          icon:'home' },
    { id:'catalog',       en:'Course Catalog',     ar:'كتالوج الدورات',       icon:'book' },
    { id:'builder',       en:'Course Builder',     ar:'منشئ الدورات',         icon:'edit' },
    { id:'assignments',   en:'Assignments',        ar:'المهام',               icon:'check' },
    { id:'team-view',     en:'All Users',          ar:'جميع المستخدمين',       icon:'users' },
    { id:'reports',       en:'Reports',            ar:'التقارير',             icon:'chart' },
    { id:'compliance',    en:'Compliance & Audit', ar:'الامتثال والمراجعة',    icon:'shield' },
    { id:'settings',      en:'Settings',           ar:'الإعدادات',            icon:'settings' },
  ],
  manager: [
    { id:'dashboard',     en:'Dashboard',          ar:'لوحة التحكم',          icon:'home' },
    { id:'team-view',     en:'My Team',            ar:'فريقي',                icon:'users' },
    { id:'catalog',       en:'Course Catalog',     ar:'كتالوج الدورات',       icon:'book' },
    { id:'reports',       en:'Team Reports',       ar:'تقارير الفريق',        icon:'chart' },
    { id:'my-learning',   en:'My Learning',        ar:'تعلمي',                icon:'play' },
  ],
  learner: [
    { id:'dashboard',     en:'My Dashboard',       ar:'لوحتي',                icon:'home' },
    { id:'my-courses',    en:'My Courses',         ar:'دوراتي',               icon:'book', badge:'dueCount' },
    { id:'catalog',       en:'Browse Catalog',     ar:'تصفح الكتالوج',         icon:'search' },
    { id:'roleplay',      en:'AI Roleplay',        ar:'محاكاة بالذكاء',        icon:'message' },
    { id:'certificates',  en:'My Certificates',    ar:'شهاداتي',              icon:'award' },
    { id:'leaderboard',   en:'Leaderboard',        ar:'لوحة المتصدرين',        icon:'trophy' },
  ],
  auditor: [
    { id:'compliance',    en:'Audit Log',          ar:'سجل المراجعة',         icon:'shield' },
    { id:'reports',       en:'Compliance Reports', ar:'تقارير الامتثال',      icon:'chart' },
    { id:'certificates',  en:'Certificate Vault',  ar:'خزينة الشهادات',       icon:'award' },
  ],
}

const AppContext = createContext(null)

export function AppProvider({ children }) {
  const [lang, setLang] = useState('en')
  const [role, setRole] = useState('learner')
  const [user, setUser] = useState(null)
  const [authed, setAuthed] = useState(false)
  const [module, setModule] = useState('dashboard')
  const [selectedMember, setSelectedMember] = useState(null)
  const [selectedCourse, setSelectedCourse] = useState(null)
  const [auditLog, setAuditLog] = useState(mockAuditLog)
  const [courses, setCourses] = useState(mockCourses)
  const [teams, setTeams] = useState(mockTeams)
  const [users, setUsers] = useState(mockUsers)
  const [learningPaths, setLearningPaths] = useState(mockLearningPaths)
  const [assignments, setAssignments] = useState(mockAssignments)
  const [certificates, setCertificates] = useState(mockCertificates)
  const [notifications, setNotifications] = useState([
    { id: 'n-1', icon: 'bell',  type: 'reminder',  read: false, ts: '2026-05-06T08:30:00Z',
      en: 'KEYNORX — Product Knowledge is due in 2 days', ar: 'كاينوركس — تنتهي مهلتها خلال يومين' },
    { id: 'n-2', icon: 'award', type: 'cert',      read: false, ts: '2026-04-30T10:14:00Z',
      en: 'Certificate issued: Diabetes 101 (92%)',       ar: 'صدرت شهادة: السكري ١٠١ (٩٢٪)' },
    { id: 'n-3', icon: 'sparkle',type: 'recommendation', read: true, ts: '2026-04-28T13:00:00Z',
      en: 'Recommended for you: ARNI Dosing — Cardiology', ar: 'موصى به: جرعات ARNI' },
  ])

  // ─────────────────────────────────────────────────────────────────────────
  // Assignment / certificate / notification mutations
  // ─────────────────────────────────────────────────────────────────────────
  // Backend endpoints (proxied server-side in production):
  //   POST /api/assignments            { courseId, userId, deadlineDays?, source? }
  //                                    → row in 'assignments' table, audit_log entry
  //   PUT  /api/assignments/:id/progress { progress: 0-100 }
  //                                    → updates status to in-progress/completed
  //   PUT  /api/assignments/:id/complete { finalScore, signatureId }
  //                                    → status='completed', issues certificate
  //   POST /api/certificates           generated by complete; returns pdf_url, qr_code
  //   GET  /api/certificates/:id/pdf   PDF binary
  //   GET  /api/notifications          for bell
  //   PUT  /api/notifications/:id/read marks read
  // ─────────────────────────────────────────────────────────────────────────
  const enrollInCourse = (courseId, opts = {}) => {
    const targetUserId = opts.userId || user?.id
    if (!targetUserId) return null
    const existing = assignments.find((a) => a.userId === targetUserId && a.courseId === courseId)
    if (existing) return existing
    const today = new Date().toISOString().slice(0, 10)
    const dueAt = new Date(Date.now() + (opts.deadlineDays || 30) * 86400000).toISOString().slice(0, 10)
    const a = {
      id: `a-${Date.now()}-${Math.random().toString(36).slice(2, 5)}`,
      userId: targetUserId,
      courseId,
      pathId: opts.pathId || null,
      assignedAt: today,
      dueAt,
      status: 'not-started',
      progress: 0,
      attempts: 0,
      finalScore: null,
      completedAt: null,
      certificateId: null,
      source: opts.source || 'self-enrolled',
    }
    setAssignments((prev) => [a, ...prev])
    return a
  }

  // Admin bulk-assign — POST /api/courses/:id/assign with body { userIds, deadlineDays, source }.
  // The server fans out one assignment row per user and emits one audit_log entry.
  const assignCourseToUsers = (courseId, userIds, opts = {}) => {
    const created = userIds
      .map((uid) => enrollInCourse(courseId, { ...opts, userId: uid }))
      .filter(Boolean)
    return created
  }

  // Builder hand-off: when admin clicks "Edit" on a catalog card, this flag tells
  // CourseBuilder to load the existing course into its draft instead of starting blank.
  const [editingCourseId, setEditingCourseId] = useState(null)

  const updateAssignmentProgress = (assignmentId, progress) => {
    setAssignments((prev) => prev.map((a) =>
      a.id === assignmentId
        ? { ...a, progress, status: progress >= 100 ? 'completed' : progress > 0 ? 'in-progress' : 'not-started' }
        : a
    ))
  }

  const completeAssignment = (assignmentId, { finalScore, signatureId } = {}) => {
    let createdCert = null
    setAssignments((prev) => prev.map((a) => {
      if (a.id !== assignmentId) return a
      const certId = `cert-${Date.now()}-${Math.random().toString(36).slice(2, 5)}`
      createdCert = {
        id: certId,
        userId: a.userId,
        courseId: a.courseId,
        issuedAt: new Date().toISOString().slice(0, 10),
        expiresAt: new Date(Date.now() + 365 * 86400000).toISOString().slice(0, 10),
        status: 'active',
        pdfUrl: `/cert/${certId}.pdf`,
        qrCode: `QR-${certId}`,
        signatureId: signatureId || null,
      }
      return {
        ...a, progress: 100, status: 'completed',
        finalScore: finalScore ?? a.finalScore ?? 0,
        completedAt: new Date().toISOString(),
        certificateId: certId,
      }
    }))
    if (createdCert) setCertificates((prev) => [createdCert, ...prev])
    return createdCert
  }

  const markNotificationRead = (id) =>
    setNotifications((prev) => prev.map((n) => n.id === id ? { ...n, read: true } : n))
  const markAllNotificationsRead = () =>
    setNotifications((prev) => prev.map((n) => ({ ...n, read: true })))

  // ── Settings (persisted to localStorage) ──────────────────────────────────
  const SETTINGS_KEY = 'avanza-lms-settings-v1'
  const DEFAULT_SETTINGS = {
    general: {
      timezone:           'Asia/Dubai',
      defaultLanguage:    'en',
      sessionTimeoutMin:  15,
      idleLockoutEnabled: true,
    },
    integrations: {
      workdayHRIS:    { enabled: true,  endpoint: '' },
      veevaCRM:       { enabled: true,  endpoint: '' },
      salesforce:     { enabled: false, endpoint: '' },
      veevaVaultQMS:  { enabled: true,  endpoint: '' },
      complianceWire: { enabled: false, endpoint: '' },
    },
    auth: {
      emailPassword:  true,
      saml:           false,
      oidc:           false,
      passwordPolicy: 'strong',
      mfa:            false,
    },
    apiKeys: {
      anthropic:    '',
      supabaseUrl:  '',
      supabaseKey:  '',
    },
    courseDefaults: {
      passMark:        80,
      attemptsAllowed: 3,
      deadlineDays:    30,
      mandatoryByDefault: false,
    },
    compliance: {
      cfrPart11:                true,
      annex11:                  true,
      gxp:                      true,
      gdpr:                     true,
      auditLogRetentionYears:   7,
      requireESignForMandatory: true,
      proctoringDefault:        false,
    },
  }
  const [settings, setSettings] = useState(() => {
    try {
      const raw = localStorage.getItem(SETTINGS_KEY)
      if (raw) {
        const parsed = JSON.parse(raw)
        return { ...DEFAULT_SETTINGS, ...parsed }
      }
    } catch (_) {}
    return DEFAULT_SETTINGS
  })

  const updateSettings = (next) => {
    setSettings(next)
    try { localStorage.setItem(SETTINGS_KEY, JSON.stringify(next)) } catch (_) {}
  }

  const resetSettings = () => {
    setSettings(DEFAULT_SETTINGS)
    try { localStorage.removeItem(SETTINGS_KEY) } catch (_) {}
  }

  const addLearningPath = (partial) => {
    const id = `lp-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`
    const path = {
      id,
      name:               partial.name || 'Untitled path',
      nameAr:             partial.nameAr || partial.name || 'مسار جديد',
      targetRoles:        partial.targetRoles || [],
      courses:            partial.courses || [],
      autoAssignTriggers: partial.autoAssignTriggers || [],
      createdAt:          new Date().toISOString(),
      createdBy:          user?.id || 'system',
    }
    setLearningPaths((prev) => [path, ...prev])
    return path
  }

  const addUsers = (records) => {
    const newTeams = []
    const newUsers = []
    const palette = [
      { col: '#1D4ED8', bg: '#EEF3FF' },
      { col: '#15803D', bg: '#DCFCE7' },
      { col: '#0E7490', bg: '#E0F7FA' },
      { col: '#7C3AED', bg: '#EDE9FE' },
      { col: '#B45309', bg: '#FEF3C7' },
      { col: '#DC2626', bg: '#FEE2E2' },
    ]
    records.forEach((r, i) => {
      const slug = (r.email || `u${i}`).split('@')[0].replace(/[^a-z0-9]/gi, '')
      const id = `t-${slug}-${Math.random().toString(36).slice(2, 5)}`
      const userId = r.userId || `u-${slug}-${Math.random().toString(36).slice(2, 5)}`
      const init = (r.name || '').split(/\s+/).filter(Boolean).map((s) => s[0]).join('').slice(0, 2).toUpperCase() || '??'
      const colors = palette[i % palette.length]
      newTeams.push({
        id, userId,
        name: r.name,
        nameAr: r.nameAr || r.name,
        init,
        col: colors.col,
        bg: colors.bg,
        role: r.jobTitle || r.role || 'Member',
        location: [r.country, r.city || r.region].filter(Boolean).join(' · ') || '—',
        completion: 0,
        avgScore: 0,
        hours: 0,
        status: 'new-hire',
        managerName: r.managerName,
        managerEmail: r.managerEmail,
        line: r.line,
        country: r.country,
        region: r.region,
        city: r.city,
        therapyArea: r.therapyArea,
        hireDate: r.hireDate,
        phone: r.phone,
        email: r.email,
        source: 'bulk-upload',
      })
      newUsers.push({
        id: userId,
        email: r.email,
        name: r.name,
        nameAr: r.nameAr || r.name,
        init,
        col: colors.col,
        bg: colors.bg,
        role: r.role || 'learner',
        scope: r.scope || null,
        managerName: r.managerName,
        managerEmail: r.managerEmail,
        line: r.line,
        country: r.country,
        region: r.region,
        city: r.city,
        therapyArea: r.therapyArea,
        jobTitle: r.jobTitle,
        hireDate: r.hireDate,
        phone: r.phone,
        activeDuty: true,
        learningIndex: 0,
      })
    })
    setTeams((prev) => [...newTeams, ...prev])
    setUsers((prev) => [...newUsers, ...prev])
    return { count: newTeams.length, ids: newTeams.map((t) => t.id) }
  }

  const addCourse = (partial) => {
    const id = `c-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`
    const today = new Date().toISOString().slice(0, 10)
    const oneYear = new Date(Date.now() + 365 * 86400000).toISOString().slice(0, 10)
    const course = {
      id,
      status: 'active',
      validFrom: today,
      validUntil: oneYear,
      durationMin: 30,
      passMark: 80,
      attemptsAllowed: 3,
      mandatory: false,
      language: 'both',
      targetRoles: [],
      tags: ['user-uploaded'],
      description: '',
      descriptionAr: '',
      version: 'v1.0.0',
      ...partial,
    }
    setCourses((prev) => [course, ...prev])
    return course
  }

  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.lang = lang
  }, [lang])

  const t = (en, ar) => (lang === 'en' ? en : ar)

  const switchLang = (l) => {
    setLang(l)
  }

  const switchRole = (r) => {
    setRole(r)
    const next = mockUsers.find((u) => u.role === r)
    if (next) setUser(next)
    setModule(NAV_CONFIG[r][0].id)
    setSelectedMember(null)
    setSelectedCourse(null)
  }

  const login = (chosenRole, email) => {
    const matchedByEmail = email ? mockUsers.find((u) => u.email.toLowerCase() === email.toLowerCase()) : null
    const finalRole = matchedByEmail ? matchedByEmail.role : chosenRole
    const finalUser = matchedByEmail || mockUsers.find((u) => u.role === finalRole) || mockUsers[0]
    setRole(finalRole)
    setUser(finalUser)
    setAuthed(true)
    setModule(NAV_CONFIG[finalRole][0].id)
    logAction('user_login', finalUser.id, { method: 'password' })
  }

  const logout = () => {
    if (user) logAction('user_logout', user.id)
    setAuthed(false)
    setSelectedMember(null)
    setSelectedCourse(null)
  }

  const logAction = (action, target, meta = {}) => {
    const entry = {
      id: `audit-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
      userId: user?.id || 'system',
      userName: user?.name || 'System',
      role: user?.role || role,
      action,
      target,
      meta,
      timestamp: new Date().toISOString(),
      ip: '10.0.0.42',
    }
    setAuditLog((prev) => [entry, ...prev])
  }

  const goto = (m) => {
    setModule(m)
    setSelectedMember(null)
  }

  const value = useMemo(() => ({
    lang, setLang, switchLang,
    role, setRole, switchRole,
    user, setUser,
    authed, login, logout,
    module, setModule, goto,
    selectedMember, setSelectedMember,
    selectedCourse, setSelectedCourse,
    t,
    nav: NAV_CONFIG[role] || [],
    users,
    addUsers,
    courses,
    addCourse,
    teams,
    assignments,
    enrollInCourse,
    assignCourseToUsers,
    editingCourseId,
    setEditingCourseId,
    updateAssignmentProgress,
    completeAssignment,
    certificates,
    notifications,
    markNotificationRead,
    markAllNotificationsRead,
    learningPaths,
    addLearningPath,
    auditLog,
    logAction,
    settings,
    updateSettings,
    resetSettings,
  }), [lang, role, user, authed, module, selectedMember, selectedCourse, auditLog, courses, teams, users, learningPaths, assignments, certificates, notifications, settings, editingCourseId])

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>
}

export function useApp() {
  const ctx = useContext(AppContext)
  if (!ctx) throw new Error('useApp must be used inside AppProvider')
  return ctx
}
